[project]
name = "giantsmind"
version = "0.1.1"
description = "A Python package that provides tools for interacting with scientific articles PDFs."
authors = [{name = "Pierre Enel", email = "pierre.enel@gmail.com"}]

dependencies = [
    "langchain",
    "langchain_community",
    "langchain_anthropic",
    "langchain_chroma",
    "llama_parse",
    "sqlalchemy",
    "pymupdf",
    "PyPDF2",
    "requests",
    "python-dotenv>=0.19.0",
    "platformdirs",
    "unstructured",
    "markdown",
    "python-levenshtein",
    "fastembed",
    "flashrank",
]

classifiers = [
   "Development Status :: 2 - Pre-Alpha",
   "Intended Audience :: Science/Research",
   "License :: OSI Approved :: BSD License",
   "Operating System :: Unix",
   "Programming Language :: Python :: 3.12",
   "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.black]
line-length = 110

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-vv"
testpaths = ["tests"]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=9.6.0",
    "pytest>=8.4.2",
]

[project.scripts]
giantsmind = "giantsmind.cli_entry:main"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "isort",
    "pytest",
    "pytest-mock",
    "ipdb",
]
